service:
    extensions: [jaeger_storage, jaeger_query, healthcheckv2]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [jaeger_storage_exporter, spanmetrics]
        metrics/spanmetrics:
            receivers: [spanmetrics]
            exporters: [prometheus]
    telemetry:
        resource:
            service.name: jaeger
        metrics:
            level: detailed
            address: 0.0.0.0:8888

extensions:
    healthcheckv2:
        use_v2: true
        http:
            endpoint: 0.0.0.0:13133
    jaeger_storage:
        backends:
            memstore:
                memory:
                    max_traces: 100000
        metric_backends:
            prom_metrics:
                prometheus:
                    endpoint: http://caramelo-prometheus:9090
                    normalize_calls: true
                    normalize_duration: true
    jaeger_query:
        storage:
            traces: memstore
            metrics: prom_metrics

receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:

exporters:
    jaeger_storage_exporter:
        trace_storage: memstore
    prometheus:
        endpoint: 0.0.0.0:8889

connectors:
    spanmetrics:
        histogram:
            explicit:
                buckets:
                    [
                        2ms,
                        4ms,
                        6ms,
                        8ms,
                        10ms,
                        50ms,
                        100ms,
                        200ms,
                        400ms,
                        800ms,
                        1s,
                        1400ms,
                        2s,
                        5s,
                        10s,
                        15s,
                    ]
        dimensions:
            - name: http.method
            - name: http.status_code
        exemplars:
            enabled: true
