// <auto-generated />
using System;
using CarameloBet.Infrastructure.Persistence.History;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarameloBet.Infrastructure.Persistence.History.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20260604173737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("history")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarameloBet.Domain.Entities.History.HistoryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BetId")
                        .HasColumnType("uuid")
                        .HasColumnName("bet_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_events_created_at");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_events_event_type");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("idx_events_round_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_events_user_id");

                    b.ToTable("events", "history");
                });
#pragma warning restore 612, 618
        }
    }
}
